# Generated by Django 3.2 on 2021-10-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('sub_title', models.CharField(max_length=450, verbose_name='sub title')),
                ('slug', models.SlugField(verbose_name='*')),
                ('img', models.ImageField(upload_to='cat_image/', verbose_name='image')),
            ],
        ),
    ]
